# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-18 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import helpers.base.jsonfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='\u540d\u79f0')),
                ('desp', models.TextField(blank=True, verbose_name='\u63cf\u8ff0')),
                ('file', models.CharField(blank=True, max_length=500, verbose_name='\u6587\u4ef6\u6750\u6599')),
            ],
        ),
        migrations.CreateModel(
            name='CunWei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='\u6751\u59d4')),
                ('zhureng', models.CharField(blank=True, max_length=100, verbose_name='\u4e3b\u4efb')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='\u7535\u8bdd\u53f7\u7801')),
            ],
        ),
        migrations.CreateModel(
            name='JianFangInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='\u59d3\u540d')),
                ('date', models.DateField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65e5\u671f')),
                ('state', models.IntegerField(blank=True, choices=[(1, '\u9547\u89c4\u4fdd\u529e\u521d\u5ba1'), (2, '\u8054\u5e2d\u4f1a\u8bae\u5ba1\u6838'), (3, '\u8054\u5408\u5ba1\u6279(\u89c4\u4fdd\u529e)'), (4, '\u8054\u5408\u5ba1\u6279(\u89c4\u571f\u6240)')], verbose_name='\u5f53\u524d\u6d41\u7a0b')),
                ('shenqing', helpers.base.jsonfield.JsonField(default=[], verbose_name='\u7533\u8bf7\u6750\u6599')),
                ('xieyi', helpers.base.jsonfield.JsonField(default=[], verbose_name='\u534f\u8bae')),
                ('cunwei', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='liantang.CunWei', verbose_name='\u6751\u59d4')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='\u540d\u79f0')),
                ('desp', models.TextField(blank=True, verbose_name='\u63cf\u8ff0')),
                ('file', models.CharField(blank=True, max_length=500, verbose_name='\u6587\u4ef6\u6750\u6599')),
            ],
        ),
        migrations.CreateModel(
            name='YinJiZhengGai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(blank=True, choices=[(1, '\u9547\u89c4\u4fdd\u529e\u521d\u5ba1'), (2, '\u8054\u5e2d\u4f1a\u8bae\u5ba1\u6838'), (3, '\u8054\u5408\u5ba1\u6279(\u89c4\u4fdd\u529e)'), (4, '\u8054\u5408\u5ba1\u6279(\u89c4\u571f\u6240)')], verbose_name='\u6574\u6539\u72b6\u6001')),
                ('date', models.DateField(blank=True, verbose_name='\u65e5\u671f')),
                ('desp', models.TextField(blank=True, verbose_name='\u8fdd\u89c4\u9879\u76ee')),
                ('file', models.CharField(blank=True, max_length=500, verbose_name='\u6838\u5b9a\u8bc1\u660e')),
                ('jianfang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liantang.JianFangInfo', verbose_name='\u5efa\u623f\u4fe1\u606f')),
            ],
        ),
    ]
