# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-18 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liantang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jianfanginfo',
            name='addr',
            field=models.CharField(blank=True, max_length=500, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='cunwei',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\u6751\u59d4'),
        ),
        migrations.AlterField(
            model_name='jianfanginfo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u59d3\u540d'),
        ),
    ]
