# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-06 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liantang', '0006_auto_20180306_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jianfanginfo',
            name='xiugai',
            field=models.TextField(blank=True, help_text='\u652f\u6301PDF\u548c\u56fe\u7247', verbose_name='\u7533\u8bf7\u4fee\u6539'),
        ),
    ]
