# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-21 05:24
from __future__ import unicode_literals

from django.db import migrations
import helpers.base.jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('liantang', '0007_auto_20180306_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applytable',
            options={'verbose_name': '\u7533\u8bf7\u8868\u683c\u8868'},
        ),
        migrations.AlterModelOptions(
            name='cunwei',
            options={'verbose_name': '\u6751\u59d4\u4fe1\u606f\u8868'},
        ),
        migrations.AlterModelOptions(
            name='jianfanginfo',
            options={'verbose_name': '\u5efa\u623f\u4fe1\u606f\u8868'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': '\u7533\u8bf7\u534f\u8bae\u8868'},
        ),
        migrations.AlterModelOptions(
            name='yinjizhenggai',
            options={'verbose_name': '\u5e94\u6025\u6574\u6539\u8868'},
        ),
        migrations.AddField(
            model_name='jianfanginfo',
            name='other',
            field=helpers.base.jsonfield.JsonField(blank=True, default=[], help_text='\u652f\u6301PDF\u548c\u56fe\u7247', verbose_name='\u5176\u4ed6'),
        ),
        migrations.AlterField(
            model_name='jianfanginfo',
            name='xieyi',
            field=helpers.base.jsonfield.JsonField(blank=True, default=[], help_text='\u652f\u6301PDF\u548c\u56fe\u7247', verbose_name='\u534f\u8bae'),
        ),
    ]
