# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-21 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liantang', '0008_auto_20180321_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jianfanginfo',
            name='other',
            field=models.TextField(blank=True, help_text='\u652f\u6301PDF\u548c\u56fe\u7247', verbose_name='\u5176\u4ed6'),
        ),
        migrations.AlterField(
            model_name='jianfanginfo',
            name='xieyi',
            field=models.TextField(blank=True, help_text='\u652f\u6301PDF\u548c\u56fe\u7247', verbose_name='\u534f\u8bae'),
        ),
    ]
