# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-27 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liantang', '0009_auto_20180321_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yinjizhenggai',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='\u65e5\u671f'),
        ),
    ]
