# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-27 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liantang', '0011_auto_20180328_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jianfanginfo',
            name='shenqing',
            field=models.TextField(default='{}', verbose_name='\u7533\u8bf7\u6750\u6599'),
        ),
    ]
