# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-06 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liantang', '0015_auto_20180329_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='JianguanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qianqi_zhunbei', models.TextField(blank=True, verbose_name='\u524d\u671f\u51c6\u5907')),
                ('zaijian_jianguan', models.TextField(blank=True, verbose_name='\u5728\u5efa\u76d1\u7ba1')),
                ('jungong_yanshou', models.TextField(blank=True, verbose_name='\u7ae3\u5de5\u9a8c\u6536')),
            ],
        ),
        migrations.AlterField(
            model_name='applytable',
            name='file',
            field=models.CharField(help_text='\u8bf7\u9009\u62e9(PDF/\u56fe\u7247)\u4e0a\u4f20', max_length=500, verbose_name='\u6587\u4ef6\u6750\u6599'),
        ),
        migrations.AlterField(
            model_name='applytable',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='jianfanginfo',
            name='state',
            field=models.IntegerField(choices=[(11, '\u6751\u59d4\u4f1a\u9884\u5ba1'), (1, '\u9547\u89c4\u4fdd\u529e\u521d\u5ba1'), (2, '\u8054\u5e2d\u4f1a\u8bae\u5ba1\u6838'), (3, '\u8054\u5408\u5ba1\u6279(\u89c4\u4fdd\u529e)'), (4, '\u8054\u5408\u5ba1\u6279(\u89c4\u571f\u6240)'), (5, '\u8054\u5408\u5ba1\u6279(\u9547\u653f\u5e9c)'), (6, '\u8054\u5408\u5ba1\u6279(\u533a\u89c4\u571f\u6240)'), (7, '\u9547\u6751\u516c\u793a'), (8, '\u5728\u5efa'), (9, '\u7ae3\u5de5\u5ba1\u6838'), (10, '\u5b8c\u7ed3')], default=11, verbose_name='\u5f53\u524d\u6d41\u7a0b'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='file',
            field=models.CharField(help_text='\u8bf7\u9009\u62e9(PDF/\u56fe\u7247)\u4e0a\u4f20', max_length=500, verbose_name='\u6587\u4ef6\u6750\u6599'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='yinjizhenggai',
            name='state',
            field=models.IntegerField(choices=[(1, '\u5f85\u5904\u7406'), (2, '\u5df2\u5904\u7406')], default=1, verbose_name='\u6574\u6539\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='jianguaninfo',
            name='jianfang',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liantang.JianFangInfo'),
        ),
    ]
